CXXFLAGS = `gsl-config --cflags` -O3 -fopenmp -I ../amplitudelib -I ../lib/include  # -I ./libbci-1.1.0/ 
LDFLAGS = `gsl-config --libs` -lm -L ../lib/lib

include filelist.m

all: bk

bk: $(OBJECTS) $(FFTOBJECTS) $(FTOBJECTS)
	g++ $(CXXFLAGS) $(LDFLAGS) $(OBJECTS) $(FFTOBJECTS) $(FTOBJECTS) -o bk 
.cpp.o:
	 g++ $(CXXFLAGS) $< -c -o $@
.c.o:
	gcc $(CXXFLAGS) $< -c -o $@

clean:
	rm -f $(FFTOBJECTS)
	rm -f $(FTOBJECTS)
	rm -f $(OBJECTS)
	rm -f bk	
